### ISSUE TITLE
Valor de parcelas e desconto não é calculado no preço especial

### ISSUE THREAD

**Issue by rjslegall** [DaviBackendorf/magento2-installment#1]
Testamos o módulo no Magento 2.4, Php 7.4

Encontramos um problema na exibição das parcelas tanto na listagem como na página do produto.
O valor de parcelas e desconto não é calculado com base no preço especial e sim no preço antigo.
A única forma de utilizar sem este problema é não usar preço especial. 

Do resto o módulo funciona perfeitamente e tem muitos recursos interessantes!

Se alguém puder ajudar seria ótimo!

**Comment by backendorf** [comment]
Olá @rjslegall, obrigado por reportar o problema, vou confirmar que o problema existe com esta configuração em uma loja zerada.

**Comment by backendorf** [comment]
@rjslegall poderia coletar e compartilhar evidencias?

**Comment by rjslegall** [comment]
Olá!

Vamos documentar este comportamento na listagem do produto:
Observe neste exemplo que tanto as parcelas como o desconto no boleto são calculados com base no preço antigo.
![image](https://user-images.githubusercontent.com/65203768/121699670-871a6280-caa5-11eb-8e86-853b28570dc5.png)

Agora vamos ver o mesmo comportamento na página do produto:
![image](https://user-images.githubusercontent.com/65203768/121700208-0f006c80-caa6-11eb-8fc0-9b8428ce62f4.png)
Na página do produto, no entanto, quando atualizado as vezes o valor passa a ser calculado no preço especial. Mas na maior parte das ocasiões o valor é calculado no preço antigo.

**Comment by backendorf** [comment]
Bom dia, problema confirmado em loja zerada.

![image](https://user-images.githubusercontent.com/37641316/121771416-9bae3780-cb45-11eb-8a5e-674a11a9c3a4.png)

**Comment by rjslegall** [comment]
Bom dia!
Obrigado pela confirmação. Tem uma previsão para lançar a correção Davi?

**Comment by backendorf** [comment]
Bom dia, já esta no forno, se tudo correr bem, sai até final deste mês.

**Comment by backendorf** [comment]
Bom dia @rjslegall correção disponível https://github.com/DaviBackendorf/magento2-installment/pull/2
Me confirme se deu certo.

**Comment by rjslegall** [comment]
Olá Davi, obrigado pelo feedback!

Acabamos de fazer vários testes. Infelizmente o problema persiste.
Observamos também que para produtos com opções personalizadas (Produtos Simples e Configuráveis) com valores maiores as parcelas não são atualizadas de acordo com a opção selecionada.

**Comment by rjslegall** [comment]
Olá!

Obrigado pela atualização. Funcionou perfeitamente agora.
