### ISSUE TITLE
Os valore de parcelamento não aparece 

### ISSUE THREAD

**Issue by ricardopantani** [DaviBackendorf/magento2-installment#10]
Os valore de parcelamento não parece.
As opções de parcelamento fica no status "Calculando..." e não carrega.
Magento 2.4.1. Não apresenta erro no console do chrome.
link:  sualojamagento.com.br 

![image](https://user-images.githubusercontent.com/45405370/199713924-afbb334e-12ec-4100-bd69-fc9afebc7060.png)

console
![image](https://user-images.githubusercontent.com/45405370/199948861-afad3f5f-3346-4358-a633-e4f2b5460785.png)

**Comment by ricardopantani** [comment]
alguém me ajuda!!! Por favor !!!!!!!!!!!!

**Comment by DaviBackendorf** [comment]
@ricardopantani parece que não acontece com a versão atualizada do Magento com o tema luma.
É provável que esse problema tenha ocorrido por causa de alguma customização do tema.
