### ISSUE TITLE
Error: Call to undefined method 

### ISSUE THREAD

**Issue by ricardopantani** [DaviBackendorf/magento2-installment#14]
Error: Call to undefined method Backendorf\Installment\Model\Config\ConfigProvider::getConfigValue() in /cloudclusters/magento/app/code/Backendorf/Installment/Model/Config/ConfigProvider.php:76
Stack trace:
#0 /cloudclusters/magento/app/code/Backendorf/Installment/Helper/Data.php(78): Backendorf\Installment\Model\Config\ConfigProvider->isModuleEnable()
#1 /cloudclusters/magento/app/code/Backendorf/Installment/Block/AllInstallments.php(76): Backendorf\Installment\Helper\Data->showAllInstallments(Object(Magento\Catalog\Model\Product\Interceptor))
#2 /cloudclusters/magento/app/code/Backendorf/Installment/view/frontend/templates/all_installments.phtml(6): Backendorf\Installment\Block\AllInstallments->renderAllInstallments()
#3 /cloudclusters/magento/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/cloudclusters/...')
#4 /cloudclusters/magento/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Backendorf\Installment\Block\AllInstallments\Interceptor), '/cloudclusters/...', Array)
#5 /cloudclusters/magento/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/cloudclusters/...')
#6 /cloudclusters/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#7 /cloudclusters/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#8 /cloudclusters/magento/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#9 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(138): Backendorf\Installment\Block\AllInstallments\Interceptor->___callParent('toHtml', Array)
#11 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(153): Backendorf\Installment\Block\AllInstallments\Interceptor->Magento\Framework\Interception\{closure}()
#12 /cloudclusters/magento/generated/code/Backendorf/Installment/Block/AllInstallments/Interceptor.php(50): Backendorf\Installment\Block\AllInstallments\Interceptor->___callPlugins('toHtml', Array, Array)
#13 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(578): Backendorf\Installment\Block\AllInstallments\Interceptor->toHtml()
#14 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('installments')
#15 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('installments')
#16 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('installments', false)
#17 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('product.info.ma...', false)
#18 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('product.info.ma...')
#19 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('product.info.ma...', false)
#20 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('product.sticky....', false)
#21 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('product.sticky....')
#22 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('product.sticky....', false)
#23 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('product.main.in...', false)
#24 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('product.main.in...')
#25 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('product.main.in...', false)
#26 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('product.main.ro...', false)
#27 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('product.main.ro...')
#28 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('product.main.ro...', false)
#29 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('product.main.co...', false)
#30 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('product.main.co...')
#31 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('product.main.co...', false)
#32 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('content', false)
#33 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('content')
#34 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('content', false)
#35 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main', false)
#36 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('main')
#37 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('main', false)
#38 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('columns', false)
#39 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#40 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('columns', false)
#41 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#42 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#43 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('main.content', false)
#44 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#45 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#46 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#47 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#48 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('root')
#49 /cloudclusters/magento/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')
#50 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#51 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#52 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#53 /cloudclusters/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#54 /cloudclusters/magento/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#55 /cloudclusters/magento/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#56 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#57 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#58 /cloudclusters/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /cloudclusters/magento/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#60 /cloudclusters/magento/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#61 /cloudclusters/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#62 /cloudclusters/magento/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#63 {main}

**Comment by DaviBackendorf** [comment]
@ricardopantani consegue passar mais detalhes do ambiente? Versão Magento, PHP ...

**Comment by DaviBackendorf** [comment]
Related https://github.com/DaviBackendorf/magento2-installment/pull/15
