### ISSUE TITLE
Apresentação do parcelamento

### ISSUE THREAD

**Issue by mrideasdesign** [DaviBackendorf/magento2-installment#7]
Eu realizei a instalação e configurei  o módulo com os valores mas na hora de exibir no produto ele apresenta o valor de 1x corretamente e em seguida o erro:

undefined undefined% no e
undefined undefined% no y
undefined undefined% no d
undefined undefined% no o
undefined undefined% no p
undefined undefined% no A
undefined undefined% no n
undefined undefined% no n
undefined undefined% no l
undefined undefined% no b
undefined undefined% no b
undefined undefined% no w
undefined undefined% no r
undefined undefined% no C
undefined undefined% no g
undefined undefined% no h
undefined undefined% no f
undefined undefined% no s
undefined undefined% no w
undefined undefined% no z
undefined undefined% no p
undefined undefined% no z
undefined undefined% no reverse
undefined undefined% no forEach
undefined undefined% no r
undefined undefined% no f
undefined undefined% no l
undefined undefined% no o
undefined undefined% no A
undefined undefined% no n
undefined undefined% no q
undefined undefined% no v
undefined undefined% no w

Você consegue me dizer uma possível solução?

**Comment by backendorf** [comment]
@mrideasdesign Bom dia, tu consegue postar aqui como que tá a tua configuração do modulo?

**Comment by mrideasdesign** [comment]
![backendorf](https://user-images.githubusercontent.com/89050554/134406293-d3d47fa0-82b2-4742-a317-ebd8df0ea7d1.png)

**Comment by mrideasdesign** [comment]
esse é a config que está no site
