### ISSUE TITLE
Apresentação do parcelamento

### ISSUE THREAD

**Issue by mrideasdesign** [DaviBackendorf/magento2-installment#8]
Eu realizei a instalação e configurei o módulo com os valores mas na hora de exibir no produto ele apresenta o valor de 1x corretamente e em seguida o erro:

undefined undefined% no e
undefined undefined% no y
undefined undefined% no d
undefined undefined% no o
undefined undefined% no p
undefined undefined% no A
undefined undefined% no n
undefined undefined% no n
undefined undefined% no l
undefined undefined% no b
undefined undefined% no b
undefined undefined% no w
undefined undefined% no r
undefined undefined% no C
undefined undefined% no g
undefined undefined% no h
undefined undefined% no f
undefined undefined% no s
undefined undefined% no w
undefined undefined% no z
undefined undefined% no p
undefined undefined% no z
undefined undefined% no reverse
undefined undefined% no forEach
undefined undefined% no r
undefined undefined% no f
undefined undefined% no l
undefined undefined% no o
undefined undefined% no A
undefined undefined% no n
undefined undefined% no q
undefined undefined% no v
undefined undefined% no w

Seguem as configurações utilizadas no painel.

Você consegue me dizer uma possível solução?
![134406293-d3d47fa0-82b2-4742-a317-ebd8df0ea7d1](https://user-images.githubusercontent.com/89050554/134816921-5937d2d5-32a5-4c92-a92b-7c6f0795d4ac.png)

**Comment by backendorf** [comment]
Olá @mrideasdesign , está muito vago, preciso de mais informações:
- Versão do Magento;
- Prints da PDP, dos erros do console,etc...
- Se possível a URL da loja (pode ser no privado);

**Comment by rafagaseo** [comment]
Não é sempre que mostra esse erro, quando esse erro ocorre e atualiza a página, retorna sem erro algum.

### Infos
Versão do Magento: 2.4.1-p1


### Print do Erro
![Screen Shot 2022-08-15 at 10 26 01](https://user-images.githubusercontent.com/4966538/184644241-60679305-2596-4ab9-8d3e-0cb02b86f60a.png)

### Configuração do Painel
![Screen Shot 2022-08-15 at 10 29 25](https://user-images.githubusercontent.com/4966538/184644376-8a8d661c-a989-499d-8b4c-0d7ade72da66.png)
![Screen Shot 2022-08-15 at 10 31 54](https://user-images.githubusercontent.com/4966538/184644868-7d94d1f3-9d36-4ec7-8ee5-e46fd3634e3c.png)



Obs: @DaviBackendorf posso mandar a página por você no privado.

**Comment by backendorf** [comment]
@mrideasdesign @rafagaseo o problema persiste? Não consegui simular, se tiverem alguma página com o problema me passem por favor.
