### ISSUE TITLE
Parcelamento desaparece do catálogo ao ordenar por: preço, posição ou nome

### ISSUE THREAD

**Issue by rjslegall** [DaviBackendorf/magento2-installment#9]
Olá!

Hoje notamos um comportamento estranho em nossa loja.
No catálogo de produtos, ao usar qualquer ferramenta da toolbar: ordenar, mostrar quantidade ou exibir em grade/lista, os parcelamentos desaparecem dos produtos até que a página seja atualizada manualmente.

![image](https://user-images.githubusercontent.com/65203768/139160539-5691fb2a-450b-4eab-918e-58a783503e23.png)

Alguém já notou este problema?

**Comment by sandiegobr** [comment]
Aqui ocorreu o problema tambem.

Acontece essas ações (ordenar, mostrar quantidade ou exibir em grade/lista) recarregam os produtos via ajax, e este módulo nao trata essa situação (refresh via ajax). Dai consegui resolver esse problema acrescentando código abaixo no arquivo view/frontend/web/js/installment.js no final de _create: function () {


```
$(document).ajaxComplete(function(event,xhr,options) {
    if (($('.item.product.product-item').length > 0) && 
        ($('.price-box.price-final_price').length > 0)) {

        $('.price-box.price-final_price').each(function (i, element) {
            widget.renderPrices(element);
            if ($(element).parents('.product-info-price').length > 0) {
                widget.updateAllInstallments(element);
            }
        });
    }
});
```

**Vai ficar como no print:**

![code1](https://user-images.githubusercontent.com/40831082/170714899-3ec33881-d7d9-4af8-a976-d6ba0f289aee.png)

**Comment by rjslegall** [comment]
Olá amigo!

Testamos e funcionou perfeitamente.
Obrigado pela ajuda!

**Comment by rjslegall** [comment]
Boa tarde!

A correção causou um comportamento estranho na página do produto.

Nos produtos que possuem opções personalizadas com aumento de valores, o valor a vista (desconto de 5%) é calculado corretamente e depois muda rapidamente para o valor original sem somar o valor personalizado.

Parece que a correção "força" a atualização desconsiderando a soma da opção personalizada.

Alguém viu este problema. Como podemos solucionar?

A correção poderia trabalhar no escopo do catálogo apenas?

**Comment by rjslegall** [comment]
Olá!

Este comportamento após a correção acima está relacionado ao meu tema Porto que tb usa ajax.
